### PR TITLE
Adding fluorescence scaffold filtering

### PR DESCRIPTION
**Pull request by jchodera**
This is an attempt to add fluorescence scaffold filtering.

Just starting PR---not ready to merge.

### CODE REVIEW

**Comment by jchodera** [comment]
I've added a violin plot of the ChEML bioactivity affinities.  I think there are likely some unreliable numbers in here, but it's kind of a neat way to visualize the potential dynamic range of affinities.
chembl_bioactivity_distributions

**Comment by sonyahanson** [comment]
Cool!

**Comment by jchodera** [comment]
Done for now!  Feel free to merge!

**Comment by jchodera** [comment]
Yay!

**Pull request merged**
